# Generated by Django 2.2.4 on 2019-08-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_event_formed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='formed',
            field=models.BooleanField(default=False),
        ),
    ]
